### ISSUE TITLE
Allow the fixing of the astrometry in the automated ROI modelling

### ISSUE THREAD

**Issue by duxfrederic** [duxfrederic/lightcurver#41]
Some datasets simply aren't good enough for a good astrometric fit. When good HST or Gaia astrometry is available, it might be beneficial to skip the optimization of the astrometry during the ROI modelling step.

**Comment by martin-millon** [comment]
Could that be done by using the Gaussian prior option of STARRED on the point source position ?

**Comment by duxfrederic** [comment]
Ah, that could be an intermediate between full freedom and full fixing. I didn't think about it, will implement it now!
